export const LOGINSTART = "LOGIN_START";
export const LOGINSUCCESS = "LOGIN_SUCCESS";
export const LOGINFAILURE = "LOGIN_FAILURE";
export const UPDATESTART = "UPDATE_START";
export const UPDATESUCCESS = "UPDATE_SUCCESS";
export const UPDATEFAILURE = "UPDATE_FAILURE";
export const LOGOUT = "LOGOUT";